spring:
  application:
    name: index-service
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: 192.168.255.131
    port: 6379
    # password: java1908
    jedis:
      pool:
        max-active: 20
server:
  port: 8760

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
