spring:
  application:
    name: email-service
  mail:
    host: smtp.qq.com
    username: xieheike@qq.com
    password: eltbhckgaxcrcacc
    default-encoding: utf-8
  redis:
    host: 192.168.255.131
    port: 6379
  # password: java1908
    jedis:
      pool:
        max-active: 20

server:
  port: 8763


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#激活邮箱的链接地址
activeServerUrl: http://localhost:8763/email/active/account/