spring:
  application:
    name: search-service
    data:
      solr:
        host: http://192.168.147.131:8983/solr/ik_core


server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  datasource:
#    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql:///qf-v6
    username: root
    password: 123
  rabbitmq:
    host: 192.168.147.131
    port: 5672
    username: rabbit
    password: 123456
    virtual-host: lxd
#imageServer: http://192.168.2.144:8888