spring:
  application:
    name: index-web
  redis:
    host: 192.168.255.131
    port: 6379
    #   password: java1908
    jedis:
      pool:
        max-active: 20

server:
  port: 7760

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
